# See https://render.com/docs/blueprint-spec
services:
  - type: web
    name: wikistumble
    env: static
    buildCommand: bin/bridgetown deploy
    staticPublishPath: ./output
    pullRequestPreviewsEnabled: true
    envVars:
      - key: BRIDGETOWN_ENV
        value: production
      - fromGroup: wikistumble-prod-envs
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-XSS-Protection
        value: "1; mode=block"
      - path: /*
        name: X-Content-Type-Options
        value: "nosniff"
      - path: /*
        name: Strict-Transport-Security
        value: "max-age=15552000; includeSubDomains"
      - path: /*
        name: Referrer-Policy
        value: "no-referrer-when-downgrade"
      - path: /*
        name: Cache-Control
        value: "public, max-age=86400, s-max-age=86400"
    routes:
      - type: rewrite
        source: /hello/*
        destination: https://wikistumble-api.onrender.com/hello/*
  - type: web
    name: wikistumble-api
    env: ruby
    plan: free
    buildCommand: bundle install && yarn install && bin/bridgetown frontend:build
    startCommand: bin/bridgetown start
    envVars:
      - key: BRIDGETOWN_ENV
        value: production
      - fromGroup: wikistumble-prod-envs
