# See https://render.com/docs/blueprint-spec
services:
  - type: web
    name: wikistumble
    env: ruby
    plan: free
    buildCommand: bundle install
    startCommand: rackup
    envVars:
      - key: RACK_ENV
        value: production
      - fromGroup: wikistumble-prod-envs
