default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bt_wikistumble_development

test: &test
  <<: *default
  database: bt_wikistumble_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: bt_wikistumble_production
